Models/Entities/Order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyamNyamWebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderedDish = new HashSet<OrderedDish>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public int ClientId { get; set; }
        public System.DateTime AppointedDT { get; set; }
        public string AppointedAddress { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedDish> OrderedDish { get; set; }
    }
}

Controllers/OrderedDishesController.cs
using NyamNyamWebAPI.Models.Entities;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NyamNyamWebAPI.Controllers
{
    public class OrderedDishesController : Controller
    {
        private NyamNyamEntities db = new NyamNyamEntities();

        // GET: OrderedDishes
        public ActionResult Index()
        {
            var orderedDish = db.OrderedDish.Include(o => o.Dish).Include(o => o.Order);
            return View(orderedDish.ToList());
        }

        // GET: OrderedDishes/Create
        public ActionResult Create()
        {
            ViewBag.DishId = new SelectList(db.Dish, "Id", "Name");
            ViewBag.OrderId = new SelectList(db.Order, "Id", "AppointedAddress");
            return View();
        }

        // POST: OrderedDishes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,DishId,ServingsNumber,StartCookingDT,EndCookingDT")] OrderedDish orderedDish,
                                   int? orderId)
        {
            if (ModelState.IsValid)
            {
                db.OrderedDish.Add(orderedDish);
                db.Order.Find(orderId).OrderedDish.Add(orderedDish);
                db.SaveChanges();
                return RedirectToAction("Details", "Orders", new { id = orderedDish.OrderId });
            }

            ViewBag.DishId = new SelectList(db.Dish, "Id", "Name", orderedDish.DishId);
            ViewBag.OrderId = new SelectList(db.Order, "Id", "AppointedAddress", orderedDish.OrderId);
            return View(orderedDish);
        }

        // GET: OrderedDishes/Edit/5
        public ActionResult Edit(int? orderId, int? dishId)
        {
            if (orderId == null || dishId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderedDish orderedDish = db.OrderedDish.Find(new object[] { orderId, dishId });
            if (orderedDish == null)
            {
                return HttpNotFound();
            }
            ViewBag.DishId = new SelectList(db.Dish, "Id", "Name", orderedDish.DishId);
            ViewBag.OrderId = new SelectList(db.Order, "Id", "AppointedAddress", orderedDish.OrderId);
            return View(orderedDish);
        }

        // POST: OrderedDishes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,DishId,ServingsNumber,StartCookingDT,EndCookingDT")] OrderedDish orderedDish)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderedDish).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Orders", new { id = orderedDish.OrderId });
            }
            ViewBag.DishId = new SelectList(db.Dish, "Id", "Name", orderedDish.DishId);
            ViewBag.OrderId = new SelectList(db.Order, "Id", "AppointedAddress", orderedDish.OrderId);
            return View(orderedDish);
        }

        // GET: OrderedDishes/Delete/5
        public ActionResult Delete(int? orderId, int? dishId)
        {
            if (orderId == null || dishId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderedDish orderedDish = db.OrderedDish.Find(new object[] { orderId, dishId });
            if (orderedDish == null)
            {
                return HttpNotFound();
            }
            return View(orderedDish);
        }

        // POST: OrderedDishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? orderId, int? dishId)
        {
            OrderedDish orderedDish = db.OrderedDish.Find(new object[] { orderId, dishId });
            db.OrderedDish.Remove(orderedDish);
            db.SaveChanges();
            return RedirectToAction("Details", "Orders", new { id = orderId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/OrdersController.cs
using NyamNyamWebAPI.Models.Entities;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NyamNyamWebAPI.Controllers
{
    public class OrdersController : Controller
    {
        private NyamNyamEntities db = new NyamNyamEntities();

        // GET: Orders
        public ActionResult Index()
        {
            var order = db.Order.Include(o => o.Client);
            return View(order.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.ClientId = new SelectList(db.Client, "Id", "Name");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ClientId,AppointedDT,AppointedAddress")] Order order)
        {
            if (ModelState.IsValid)
            {
                order.CreatedDT = System.DateTime.Now;
                db.Order.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClientId = new SelectList(db.Client, "Id", "Name", order.ClientId);
            return RedirectToAction("Details", "Orders", new { id = order.Id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Orders/Create.cshtml
@model NyamNyamWebAPI.Models.Entities.Order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, "Client", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppointedDT, "Appointment date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppointedDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AppointedDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppointedAddress, "Appointment address", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppointedAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AppointedAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Orders/Details.cshtml
@model NyamNyamWebAPI.Models.Entities.Order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Creation time
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDT)
        </dd>

        <dt>
            Appointment time
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppointedDT)
        </dd>

        <dt>
            Appointed address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppointedAddress)
        </dd>

        <dt>
            Client full name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.Name)
        </dd>

    </dl>
</div>

<h2>Ordered dishes</h2>

<table class="table">
    <tr>
        <th>
            Servings number
        </th>
        <th>
            Date and time of start cooking
        </th>
        <th>
            Date and time of end cooking
        </th>
        <th>
            Dish name
        </th>
        <th>
            Appointed address
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.OrderedDish)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ServingsNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartCookingDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndCookingDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dish.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Order.AppointedAddress)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "OrderedDishes", new { OrderId = Model.Id, DishId = item.DishId }, null) |
                @Html.ActionLink("Delete", "Delete", "OrderedDishes", new { OrderId = Model.Id, DishId = item.DishId }, null)
            </td>
        </tr>
    }

</table>

<p>
    @Html.ActionLink("Add ordered dish", "Create", "OrderedDishes", new { OrderId = Model.Id }, null) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Orders/Index.cshtml
@model IEnumerable<NyamNyamWebAPI.Models.Entities.Order>

@{
    ViewBag.Title = "Orders";
}

<h2>Orders</h2>

<p>
    @Html.ActionLink("Create a new order", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Creation time
        </th>
        <th>
            Appointment time
        </th>
        <th>
            Appointed address
        </th>
        <th>
            Client full name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppointedDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppointedAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client.Name)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
        </tr>
    }

</table>